### ISSUE TITLE
STackFrame filtering

### ISSUE THREAD

**Issue by Arkoniak** [timholy/FlameGraphs.jl#11]
I think it would be nice to have filtering feature as in https://github.com/DevJac/OwnTime, only filter all calls starting from some point. Sometimes there is too much information in the graph, which is irrelevant.

**Comment by timholy** [comment]
Do you mean "starting from some point" meaning only the base of the tree, or just drop all nodes that don't match? I think the latter would be problematic, but I could buy into the former.

Not hard at all. Care to try a PR or is that too daunting?
