### ISSUE TITLE
Package broken due to broken LeftChildRightSiblingTrees

### ISSUE THREAD

**Issue by lassepe** [timholy/FlameGraphs.jl#57]
LeftChildRightSiblingTrees v0.1.3 (which is the latest allowed version for this package) extends `AbstractTrees.parentlinks` which does not seem to exist. As a result `LeftChildRightSiblingTrees.jl` does not pre-compile, rendering FlameGraphs.jl (and thereby ProfileView.jl) unusable right now.

**Comment by timholy** [comment]
Presumably this was fixed by #58
